{
 "title": "MTA Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "label_values(up,app)" } },
   { "name": "instance", "query": { "query": "label_values(up,instance)" } },
   { "name": "job", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "description": "Server name",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "server_info{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "server_info{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_players_total{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gamemode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "server_info{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - server_start_timestamp{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min client version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "server_info{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server FPS sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_fps_sync{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server FPS sync (logic)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_fps_sync_logic{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_total{app=\"$app\", instance=\"$instance\", job=\"$job\", state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resources_total{app=\"$app\", instance=\"$instance\", job=\"$job\", state=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logic thread CPU (avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_logic_thread_cpu_usage_avg{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync thread CPU (avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_sync_thread_cpu_usage_avg{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raknet thread CPU (avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_raknet_thread_cpu_usage_avg{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_memory_usage_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_network_incoming_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_network_outgoing_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming packets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_network_incoming_packets{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing packets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_network_outgoing_packets{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing packets loss",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_network_outgoing_packets_loss{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(network_received_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}[1m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(network_sent_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}[1m])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(network_received_packets{app=\"$app\", instance=\"$instance\", job=\"$job\"}[1m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(network_sent_packets{app=\"$app\", instance=\"$instance\", job=\"$job\"}[1m])",
     "legendFormat": "sent"
    },
    {
     "expr": "network_send_buffer_messages{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "send_buffer"
    },
    {
     "expr": "network_resend_buffer_messages{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "resend_buffer"
    }
   ]
  },
  {
   "title": "Network Packets Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_packet_loss_total{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "loss"
    },
    {
     "expr": "network_packet_loss_last_second{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "loss_last_second"
    }
   ]
  },
  { "title": "Process memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  { "title": "Lua timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Lua Timing CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "lua_timing_cpu_usage{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Lua Timing CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lua_timing_cpu_time{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Lua memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Lua memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "lua_memory_usage{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Lua elements",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lua_memory_elements_total{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Lua events",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lua_memory_events_total{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Lua timers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lua_memory_timers_total{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Packet usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Packet Usage Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "packet_usage_incoming_messages{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{packet_type}}"
    }
   ]
  },
  {
   "title": "Packet Usage Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "packet_usage_outgoing_messages{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{packet_type}}"
    }
   ]
  },
  {
   "title": "Packet Usage Incoming Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "packet_usage_incoming_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{packet_type}}"
    }
   ]
  },
  {
   "title": "Packet Usage Outgoing Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "packet_usage_outgoing_bytes{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{packet_type}}"
    }
   ]
  },
  {
   "title": "Packet Usage Incoming CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "packet_usage_incoming_cpu_usage{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{packet_type}}"
    }
   ]
  },
  {
   "title": "Packet Usage Outgoing Messages Share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "packet_usage_outgoing_messages_share{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{packet_type}}"
    }
   ]
  },
  { "title": "Event packet usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Event packet usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "event_packet_usage_messages{app=\"$app\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{packet_type}}:{{packet_name}}"
    }
   ]
  }
 ]
}